use crate::daemon::virtual_monitor::VirtualMonitorManager;
use std::sync::Arc;
use tokio::io::AsyncReadExt;
use tokio::net::TcpListener;
use tokio::sync::{watch, Mutex};

/// Magic byte header prefix identifying a valid binary input packet ('S' = 0x53).
pub const BINARY_MAGIC_HEADER: u8 = 0x53;

/// High-level input events generated by client touch, active stylus, or gesture events.
#[derive(Debug, Clone, PartialEq)]
pub enum InputEvent {
    /// Touch movement event with normalized coordinates (0.0..1.0) and finger slot ID.
    TouchMove { x: f32, y: f32, id: i32 },
    /// Touch down event with normalized coordinates (0.0..1.0) and finger slot ID.
    TouchDown { x: f32, y: f32, id: i32 },
    /// Touch release event with normalized coordinates (0.0..1.0) and finger slot ID.
    TouchUp { x: f32, y: f32, id: i32 },
    /// Scroll axis event with horizontal (`dx`) and vertical (`dy`) displacement deltas.
    Scroll { dx: f32, dy: f32 },
    /// Contextual right-click event at normalized screen coordinates (0.0..1.0).
    RightClick { x: f32, y: f32 },
    /// Overview toggle gesture event (e.g. 3-finger tap or threshold swipe).
    OverviewGesture,
    /// Smooth 1:1 swipe gesture delta event with horizontal (`dx`) and vertical (`dy`) deltas.
    SwipeGesture { dx: f32, dy: f32 },
    /// Active stylus motion event with normalized coordinates, pressure, and tilt values.
    StylusMove {
        x: f32,
        y: f32,
        pressure: f32,
        tilt_x: f32,
        tilt_y: f32,
    },
    /// Active stylus contact event with normalized coordinates, pressure, and tilt values.
    StylusDown {
        x: f32,
        y: f32,
        pressure: f32,
        tilt_x: f32,
        tilt_y: f32,
    },
    /// Active stylus release event at normalized coordinates.
    StylusUp { x: f32, y: f32 },
    /// Initial resolution handshake packet sent by client device on connection.
    InitResolution { width: u32, height: u32 },
}

/// Manages input event processing and forwarding to the virtual display manager.
pub struct InputInjector {
    _screen_width: u32,
    _screen_height: u32,
    vm_manager: Option<Arc<Mutex<VirtualMonitorManager>>>,
}

impl InputInjector {
    /// Creates a new `InputInjector` instance configured with screen bounds and a virtual monitor manager handle.
    pub fn new(
        screen_width: u32,
        screen_height: u32,
        vm_manager: Option<Arc<Mutex<VirtualMonitorManager>>>,
    ) -> Result<Self, String> {
        tracing::info!(
            "Initializing Virtual Input Injector (Bounds: {}x{})",
            screen_width,
            screen_height
        );
        Ok(Self {
            _screen_width: screen_width,
            _screen_height: screen_height,
            vm_manager,
        })
    }

    /// Asynchronously dispatches an `InputEvent` to the active virtual display manager.
    pub async fn process_event(&self, event: InputEvent) {
        let vm_opt = self.vm_manager.clone();

        match &event {
            InputEvent::TouchDown { x, y, id } => {
                let norm_x = (*x as f64).clamp(0.0, 1.0);
                let norm_y = (*y as f64).clamp(0.0, 1.0);
                let slot = *id as u32;
                tracing::info!(
                    "TOUCH DOWN [{}] -> Norm ({:.4}, {:.4})",
                    slot,
                    norm_x,
                    norm_y
                );
                if let Some(vm_arc) = vm_opt {
                    let vm = vm_arc.lock().await;
                    let _ = vm.notify_touch_down(slot, norm_x, norm_y).await;
                }
            }
            InputEvent::TouchMove { x, y, id } => {
                let norm_x = (*x as f64).clamp(0.0, 1.0);
                let norm_y = (*y as f64).clamp(0.0, 1.0);
                let slot = *id as u32;
                tracing::trace!(
                    "TOUCH MOVE [{}] -> Norm ({:.4}, {:.4})",
                    slot,
                    norm_x,
                    norm_y
                );
                if let Some(vm_arc) = vm_opt {
                    let vm = vm_arc.lock().await;
                    let _ = vm.notify_touch_motion(slot, norm_x, norm_y).await;
                }
            }
            InputEvent::TouchUp { x, y, id } => {
                let norm_x = (*x as f64).clamp(0.0, 1.0);
                let norm_y = (*y as f64).clamp(0.0, 1.0);
                let slot = *id as u32;
                tracing::info!(
                    "TOUCH RELEASE [{}] -> Norm ({:.4}, {:.4})",
                    slot,
                    norm_x,
                    norm_y
                );
                if let Some(vm_arc) = vm_opt {
                    let vm = vm_arc.lock().await;
                    let _ = vm.notify_touch_up(slot).await;
                }
            }
            InputEvent::Scroll { dx, dy } => {
                tracing::info!("SCROLL EVENT -> dx: {:.2}, dy: {:.2}", dx, dy);
                if let Some(vm_arc) = vm_opt {
                    let vm = vm_arc.lock().await;
                    let scroll_scale = 0.18;
                    // Natural scroll direction (-dx, -dy) matching mobile and GNOME touchpad physics
                    let _ = vm
                        .notify_scroll(-(*dx as f64) * scroll_scale, -(*dy as f64) * scroll_scale)
                        .await;
                }
            }

            InputEvent::RightClick { x, y } => {
                let norm_x = (*x as f64).clamp(0.0, 1.0);
                let norm_y = (*y as f64).clamp(0.0, 1.0);
                tracing::info!("RIGHT CLICK EVENT -> Norm ({:.4}, {:.4})", norm_x, norm_y);
                if let Some(vm_arc) = vm_opt {
                    let vm = vm_arc.lock().await;
                    let _ = vm.notify_right_click(norm_x, norm_y).await;
                }
            }
            InputEvent::OverviewGesture => {
                tracing::info!("GESTURE OVERVIEW EVENT");
                if let Some(vm_arc) = vm_opt {
                    let vm = vm_arc.lock().await;
                    let _ = vm.notify_overview_toggle().await;
                }
            }
            InputEvent::SwipeGesture { dx, dy } => {
                tracing::info!("SWIPE GESTURE -> dx: {:.2}, dy: {:.2}", dx, dy);
                if let Some(vm_arc) = vm_opt {
                    let vm = vm_arc.lock().await;
                    let _ = vm.notify_swipe_gesture(*dx as f64, *dy as f64).await;
                }
            }
            InputEvent::StylusDown {
                x,
                y,
                pressure,
                tilt_x,
                tilt_y,
            } => {
                let norm_x = (*x as f64).clamp(0.0, 1.0);
                let norm_y = (*y as f64).clamp(0.0, 1.0);
                tracing::info!(
                    "STYLUS DOWN -> Norm ({:.4}, {:.4}) Pressure: {:.2} Tilt: ({:.1}, {:.1})",
                    norm_x,
                    norm_y,
                    pressure,
                    tilt_x,
                    tilt_y
                );
                if let Some(vm_arc) = vm_opt {
                    let vm = vm_arc.lock().await;
                    let _ = vm
                        .notify_stylus_down(norm_x, norm_y, *pressure, *tilt_x, *tilt_y)
                        .await;
                }
            }
            InputEvent::StylusMove {
                x,
                y,
                pressure,
                tilt_x,
                tilt_y,
            } => {
                let norm_x = (*x as f64).clamp(0.0, 1.0);
                let norm_y = (*y as f64).clamp(0.0, 1.0);
                tracing::trace!(
                    "STYLUS MOVE -> Norm ({:.4}, {:.4}) Pressure: {:.2} Tilt: ({:.1}, {:.1})",
                    norm_x,
                    norm_y,
                    pressure,
                    tilt_x,
                    tilt_y
                );
                if let Some(vm_arc) = vm_opt {
                    let vm = vm_arc.lock().await;
                    let _ = vm
                        .notify_stylus_move(norm_x, norm_y, *pressure, *tilt_x, *tilt_y)
                        .await;
                }
            }
            InputEvent::StylusUp { x, y } => {
                let norm_x = (*x as f64).clamp(0.0, 1.0);
                let norm_y = (*y as f64).clamp(0.0, 1.0);
                tracing::info!("STYLUS RELEASE -> Norm ({:.4}, {:.4})", norm_x, norm_y);
                if let Some(vm_arc) = vm_opt {
                    let vm = vm_arc.lock().await;
                    let _ = vm.notify_stylus_up(norm_x, norm_y).await;
                }
            }
            InputEvent::InitResolution { width, height } => {
                tracing::info!(
                    "HANDSHAKE: Tablet Native Resolution -> {}x{}",
                    width,
                    height
                );
                if let Some(vm_arc) = vm_opt {
                    let mut vm = vm_arc.lock().await;
                    vm.update_target_resolution(*width, *height);
                }
            }
        }
    }
}

/// Parses a 20-byte binary packet starting with magic header `0x53`.
///
/// ### Packet Layout (20 Bytes Little-Endian)
/// - `[0]`: Magic Header Byte (`0x53` = 'S')
/// - `[1]`: Event type code (`u8`)
/// - `[2..4]`: Finger slot ID or flags (`u16` LE)
/// - `[4..8]`: Parameter 1 (`f32` LE - `norm_x`, `dx`, `width`)
/// - `[8..12]`: Parameter 2 (`f32` LE - `norm_y`, `dy`, `height`)
/// - `[12..16]`: Parameter 3 (`f32` LE - `pressure`)
/// - `[16..20]`: Parameter 4 (`f32` LE - `tilt_x`)
pub fn parse_binary_packet(bytes: &[u8; 20]) -> Option<InputEvent> {
    if bytes[0] != BINARY_MAGIC_HEADER {
        return None;
    }

    let event_type = bytes[1];
    let slot = u16::from_le_bytes([bytes[2], bytes[3]]) as i32;
    let param1 = f32::from_le_bytes([bytes[4], bytes[5], bytes[6], bytes[7]]);
    let param2 = f32::from_le_bytes([bytes[8], bytes[9], bytes[10], bytes[11]]);
    let param3 = f32::from_le_bytes([bytes[12], bytes[13], bytes[14], bytes[15]]);
    let param4 = f32::from_le_bytes([bytes[16], bytes[17], bytes[18], bytes[19]]);

    match event_type {
        0x01 => Some(InputEvent::TouchDown {
            x: param1,
            y: param2,
            id: slot,
        }),
        0x02 => Some(InputEvent::TouchMove {
            x: param1,
            y: param2,
            id: slot,
        }),
        0x03 => Some(InputEvent::TouchUp {
            x: param1,
            y: param2,
            id: slot,
        }),
        0x04 => Some(InputEvent::StylusDown {
            x: param1,
            y: param2,
            pressure: param3,
            tilt_x: param4,
            tilt_y: 0.0,
        }),
        0x05 => Some(InputEvent::StylusMove {
            x: param1,
            y: param2,
            pressure: param3,
            tilt_x: param4,
            tilt_y: 0.0,
        }),
        0x06 => Some(InputEvent::StylusUp {
            x: param1,
            y: param2,
        }),
        0x07 => Some(InputEvent::Scroll {
            dx: param1,
            dy: param2,
        }),
        0x08 => Some(InputEvent::RightClick {
            x: param1,
            y: param2,
        }),
        0x09 => Some(InputEvent::OverviewGesture),
        0x0A => Some(InputEvent::InitResolution {
            width: param1 as u32,
            height: param2 as u32,
        }),
        0x0B => Some(InputEvent::SwipeGesture {
            dx: param1,
            dy: param2,
        }),
        _ => None,
    }
}

/// Asynchronous TCP server listener accepting remote input client socket connections.
pub struct InputServer {
    stop_tx: Option<watch::Sender<bool>>,
}

impl InputServer {
    /// Starts listening for input TCP socket connections on the specified port.
    pub fn start(injector: Arc<InputInjector>, port: u16) -> Self {
        let (stop_tx, mut stop_rx) = watch::channel(false);

        tokio::spawn(async move {
            let addr = format!("127.0.0.1:{}", port);
            tracing::info!("Starting Input Event TCP Listener on {}", addr);
            let listener = match TcpListener::bind(&addr).await {
                Ok(l) => l,
                Err(e) => {
                    tracing::error!("Failed to bind input listener on {}: {}", addr, e);
                    return;
                }
            };

            loop {
                tokio::select! {
                    _ = stop_rx.changed() => {
                        if *stop_rx.borrow() {
                            tracing::info!("Stopping Input Event TCP Listener");
                            break;
                        }
                    }
                    accept_res = listener.accept() => {
                        match accept_res {
                            Ok((mut stream, peer)) => {
                                tracing::info!("Input Client Connected from {}", peer);
                                let injector_clone = injector.clone();
                                let mut stop_rx_client = stop_rx.clone();

                                tokio::spawn(async move {
                                    let mut buffer = Vec::with_capacity(1024);
                                    let mut temp_buf = [0u8; 512];

                                    loop {
                                        tokio::select! {
                                            _ = stop_rx_client.changed() => {
                                                if *stop_rx_client.borrow() { break; }
                                            }
                                            read_res = stream.read(&mut temp_buf) => {
                                                match read_res {
                                                    Ok(0) => {
                                                        tracing::info!("Input Client Disconnected");
                                                        break;
                                                    }
                                                    Ok(n) => {
                                                        buffer.extend_from_slice(&temp_buf[..n]);

                                                        while !buffer.is_empty() {
                                                            if buffer[0] != BINARY_MAGIC_HEADER {
                                                                tracing::warn!(
                                                                    "Discarding unexpected byte 0x{:02x} while resyncing input stream",
                                                                    buffer[0]
                                                                );
                                                                buffer.remove(0);
                                                                continue;
                                                            }
                                                            if buffer.len() < 20 {
                                                                break; // Need more bytes
                                                            }
                                                            let mut pkt_bytes = [0u8; 20];
                                                            pkt_bytes.copy_from_slice(&buffer[..20]);
                                                            buffer.drain(..20);

                                                            if let Some(event) = parse_binary_packet(&pkt_bytes) {
                                                                injector_clone.process_event(event).await;
                                                            } else {
                                                                tracing::warn!("Invalid binary packet received");
                                                            }
                                                        }
                                                    }
                                                    Err(e) => {
                                                        tracing::warn!("Error reading input socket: {}", e);
                                                        break;
                                                    }
                                                }
                                            }
                                        }
                                    }
                                });
                            }
                            Err(e) => {
                                tracing::warn!("Failed to accept input socket connection: {}", e);
                            }
                        }
                    }
                }
            }
        });

        Self {
            stop_tx: Some(stop_tx),
        }
    }

    /// Stops the input TCP socket server.
    pub fn stop(&mut self) {
        if let Some(tx) = self.stop_tx.take() {
            let _ = tx.send(true);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_binary_touch_down() {
        let mut pkt = [0u8; 20];
        pkt[0] = BINARY_MAGIC_HEADER;
        pkt[1] = 0x01; // TOUCH_DOWN
        pkt[2..4].copy_from_slice(&1u16.to_le_bytes()); // slot 1
        pkt[4..8].copy_from_slice(&0.5f32.to_le_bytes()); // x
        pkt[8..12].copy_from_slice(&0.75f32.to_le_bytes()); // y

        let event = parse_binary_packet(&pkt).expect("Should parse touch down packet");
        assert_eq!(
            event,
            InputEvent::TouchDown {
                x: 0.5,
                y: 0.75,
                id: 1
            }
        );
    }

    #[test]
    fn test_parse_binary_stylus_down() {
        let mut pkt = [0u8; 20];
        pkt[0] = BINARY_MAGIC_HEADER;
        pkt[1] = 0x04; // STYLUS_DOWN
        pkt[4..8].copy_from_slice(&0.25f32.to_le_bytes()); // x
        pkt[8..12].copy_from_slice(&0.60f32.to_le_bytes()); // y
        pkt[12..16].copy_from_slice(&0.85f32.to_le_bytes()); // pressure
        pkt[16..20].copy_from_slice(&15.0f32.to_le_bytes()); // tilt_x

        let event = parse_binary_packet(&pkt).expect("Should parse stylus down packet");
        assert_eq!(
            event,
            InputEvent::StylusDown {
                x: 0.25,
                y: 0.60,
                pressure: 0.85,
                tilt_x: 15.0,
                tilt_y: 0.0,
            }
        );
    }

    #[test]
    fn test_parse_binary_swipe_gesture() {
        let mut pkt = [0u8; 20];
        pkt[0] = BINARY_MAGIC_HEADER;
        pkt[1] = 0x0B; // SWIPE_GESTURE
        pkt[4..8].copy_from_slice(&12.5f32.to_le_bytes()); // dx
        pkt[8..12].copy_from_slice(&(-45.0f32).to_le_bytes()); // dy

        let event = parse_binary_packet(&pkt).expect("Should parse swipe gesture");
        assert_eq!(
            event,
            InputEvent::SwipeGesture {
                dx: 12.5,
                dy: -45.0
            }
        );
    }

    #[test]
    fn test_parse_binary_invalid_magic() {
        let mut pkt = [0u8; 20];
        pkt[0] = 0x00; // Invalid magic
        assert_eq!(parse_binary_packet(&pkt), None);
    }

}
